# vim:tw=200
---
user_email: 'ahmed@miro.com'
keychain_name: gmail.com
imap_server: imap.gmail.com
smtp_server: smtp.gmail.com
mail_accounts:
  - name: 'Work'
    imap_server: '{{ imap_server }}'
    imap_user: '{{ user_email }}'
    imap_keychain_account: '{{ keychain_account }}'
    imap_keychain_name: '{{ keychain_name }}'

    smtp_server: '{{ smtp_server }}'
    smtp_from: '{{ user_email }}'
    smtp_user: '{{ user_email }}'
    smtp_keychain_account: '{{ keychain_account }}'
    smtp_keychain_name: '{{ keychain_name }}'

    account_color: color238
