# vim:tw=200
---
- name: find all files/directories in '{{ ansible_env.PWD | relpath }}/roles/dotfiles/files'
  find:
    paths: '{{ ansible_env.PWD }}/roles/dotfiles/files'
    excludes: '.DS_Store,.config,.ssh'
    file_type: any
    hidden: yes
  register: files

- name: find all directories in '{{ ansible_env.PWD | relpath }}/roles/dotfiles/files/.config'
  find:
    paths: '{{ ansible_env.PWD }}/roles/dotfiles/files/.config'
    excludes: '.DS_Store,gnupg,weechat'
    file_type: directory
    hidden: yes
  register: config_dirs

- name: find all templates in '{{ ansible_env.PWD | relpath }}/roles/dotfiles/templates'
  find:
    paths: '{{ ansible_env.PWD }}/roles/dotfiles/templates'
    recurse: yes
    file_type: file
    excludes: '.DS_Store,account'
    hidden: yes
  register: templates

- name: create directories that we shouldn't manage
  file: path="{{ item }}" state=directory
  with_items:
    - ~/.config
    - ~/.config/gnupg
    - ~/.config/weechat
    - ~/.config/msmtp
    - ~/.config/notmuch
    - ~/.mail
    - ~/.mail/.notmuch/hooks
    - ~/.mail/Personal
    - ~/.mail/Work
    - ~/.ssh
  loop_control:
    label: '{{ item }}'

- name: symlink files
  with_items: '{{ files.files + config_dirs.files }}'
  vars:
    path: '{{ item.path | relpath | regex_replace("roles/dotfiles/files/", "") | dirname }}'
    dest: "~/{{ path + '/' if path != '' else '' }}{{ item.path | basename }}"
  file:
    src: '{{ item.path }}'
    path: '{{ dest }}'
    state: link
    force: true
  loop_control:
    label: '{{ item.path | relpath }} -> {{ dest }}'

# Dynamically create folders for templates if they don't exist
- name: symlink templates
  with_items: '{{ templates.files }}'
  vars:
    path: '{{ item.path | relpath | regex_replace("roles/dotfiles/templates/", "") | dirname }}'
    dest: "~/{{ path + '/' if path != '' else '' }}{{ item.path | basename }}"
  template:
    src: '{{ item.path }}'
    dest: '{{ dest }}'
  loop_control:
    label: '{{ item.path | relpath }} -> {{ dest }}'

- name: symlink neovim & mutt
  file: path={{ item.path }} src={{ item.src }} state=link force=yes
  loop_control:
    label: '{{ item.path }}'
  loop:
    - title: 'nvim to vim'
      path: ~/.config/nvim
      src: ~/.vim
    - title: 'mutt to neomutt'
      path: ~/.config/mutt
      src: ~/.config/neomutt

- name: create accounts directory
  file: path="~/.config/neomutt/accounts" state=directory

- name: generate mail accounts
  with_items: '{{ mail_accounts }}'
  when: item.imap_user != ''
  loop_control:
    label: '{{ item.name }}: {{ item.imap_user }}'
  template:
    src: '{{ ansible_env.PWD }}/roles/dotfiles/templates/.config/neomutt/accounts/account'
    dest: '~/.config/neomutt/accounts/{{ item.name }}'
