---
- name:
    dotfiles | find all directories in '{{ ansible_env.PWD | expanduser
    }}/roles/dotfiles/files'
  find:
    paths: '{{ ansible_env.PWD }}/roles/dotfiles/files'
    recurse: yes
    file_type: directory
    hidden: yes
  register: dirs

- name:
    dotfiles | find all files in '{{ ansible_env.PWD | expanduser
    }}/roles/dotfiles/files'
  find:
    paths: '{{ ansible_env.PWD }}/roles/dotfiles/files'
    recurse: yes
    file_type: file
    excludes: '.DS_Store,.gitkeep,.gitignore'
    hidden: yes
  register: files

- name:
    dotfiles | find all templates in '{{ ansible_env.PWD | expanduser
    }}/roles/dotfiles/templates'
  find:
    paths: '{{ ansible_env.PWD }}/roles/dotfiles/templates'
    recurse: yes
    file_type: file
    excludes: '.DS_Store,.gitkeep,.gitignore,account'
    hidden: yes
  register: templates

# - debug:
#     msg="Dirs {{ item.path | relpath | regex_replace('roles/dotfiles/files/',
#     '') }}"
#   with_items: '{{ dirs.files }}'
#
# - debug:
#     msg="Files {{ item.path | basename }} {{ item.path | dirname }} {{ item.path
#     | relpath }} {{ item.path | relpath | regex_replace('roles/dotfiles/files/',
#     '') | dirname }}"
#   with_items: '{{ files.files }}'
#
# - debug:
#     msg="Files {{ item.path | basename }} {{ item.path | dirname }} {{ item.path
#     | relpath }} {{ item.path | relpath |
#     regex_replace('roles/dotfiles/templates/', '') | dirname }}"
#   with_items: '{{ templates.files }}'
#
- name: dotfiles | create directories
  file:
    path="~/{{ item.path | relpath | regex_replace('roles/dotfiles/files/', '')
    }}" state=directory
  with_items: '{{ dirs.files }}'

- name: dotfiles | symlink files
  with_items: '{{ files.files }}'
  vars:
    path:
      '{{ item.path | relpath | regex_replace("roles/dotfiles/files/", "") |
      dirname }}'
  file:
    src: '{{ item.path }}'
    path: "~/{{ path + '/' if path != '' else '' }}{{ item.path | basename }}"
    state: link
    force: true

- name: dotfiles | symlink templates
  with_items: '{{ templates.files }}'
  vars:
    path:
      '{{ item.path | relpath | regex_replace("roles/dotfiles/templates/", "") |
      dirname }}'
  template:
    src: '{{ item.path }}'
    dest: "~/{{ path + '/' if path != '' else '' }}{{ item.path | basename }}"

- name: dotfiles | symlink {{ item.name }}
  file: path={{ item.path }} src={{ item.src }} state=link force=yes
  loop:
    - title: 'nvim to vim'
      path: ~/.config/nvim
      src: ~/.vim
    - title: 'mutt to neomutt'
      path: ~/.config/mutt
      src: ~/.config/neomutt

- name: dotfiles | generate mail accounts
  with_items: '{{ mail_accounts }}'
  template:
    src:
      '{{ ansible_env.PWD
      }}/roles/dotfiles/templates/.config/neomutt/accounts/account'
    dest: '~/.config/neomutt/accounts/{{ item.name }}'
