# vim:tw=200
---
- name: dotfiles | find all directories in '{{ ansible_env.PWD | expanduser }}/roles/dotfiles/files'
  find:
    paths: '{{ ansible_env.PWD }}/roles/dotfiles/files'
    recurse: yes
    file_type: directory
    hidden: yes
  register: dirs

- name: dotfiles | find all files in '{{ ansible_env.PWD | expanduser }}/roles/dotfiles/files'
  find:
    paths: '{{ ansible_env.PWD }}/roles/dotfiles/files'
    recurse: yes
    file_type: file
    excludes: '.DS_Store,.gitkeep,.gitignore'
    hidden: yes
  register: files

- name: dotfiles | find all templates in '{{ ansible_env.PWD | expanduser }}/roles/dotfiles/templates'
  find:
    paths: '{{ ansible_env.PWD }}/roles/dotfiles/templates'
    recurse: yes
    file_type: file
    excludes: '.DS_Store,.gitkeep,.gitignore,account'
    hidden: yes
  register: templates

- name: dotfiles | create directories
  vars:
    path: "~/{{ item.path | relpath | regex_replace('roles/dotfiles/files/', '') }}"
  file: path="{{ path }}" state=directory
  with_items: '{{ dirs.files }}'
  loop_control:
    label: '{{ item.path | relpath }} -> {{ path }}'

- name: dotfiles | symlink files
  with_items: '{{ files.files }}'
  vars:
    path: '{{ item.path | relpath | regex_replace("roles/dotfiles/files/", "") | dirname }}'
    dest: "~/{{ path + '/' if path != '' else '' }}{{ item.path | basename }}"
  file:
    src: '{{ item.path }}'
    path: '{{ dest }}'
    state: link
    force: true
  loop_control:
    label: '{{ item.path | relpath }} -> {{ dest }}'

- name: dotfiles | symlink templates
  with_items: '{{ templates.files }}'
  vars:
    path: '{{ item.path | relpath | regex_replace("roles/dotfiles/templates/", "") | dirname }}'
    dest: "~/{{ path + '/' if path != '' else '' }}{{ item.path | basename }}"
  template:
    src: '{{ item.path }}'
    dest: '{{ dest }}'
  loop_control:
    label: '{{ item.path | relpath }} -> {{ dest }}'

- name: dotfiles | symlink {{ item.name }}
  file: path={{ item.path }} src={{ item.src }} state=link force=yes
  loop_control:
    label: '{{ item.path }}'
  loop:
    - title: 'nvim to vim'
      path: ~/.config/nvim
      src: ~/.vim
    - title: 'mutt to neomutt'
      path: ~/.config/mutt
      src: ~/.config/neomutt

- name: dotfiles | generate mail accounts
  with_items: '{{ mail_accounts }}'
  loop_control:
    label: '{{ item.name }}: {{ item.imap_user }}'
  template:
    src: '{{ ansible_env.PWD }}/roles/dotfiles/templates/.config/neomutt/accounts/account'
    dest: '~/.config/neomutt/accounts/{{ item.name }}'
