# vim:tw=200
---
- name: create (local) LaunchAgents directory
  file: path="~/Library/LaunchAgents" state=directory

- name: configure (local) LaunchAgents
  template:
    src: com.ahmedelgabri.isync.plist
    dest: '~/Library/LaunchAgents/com.ahmedelgabri.isync.plist'
