# vim:tw=200
---
# [note] This task depends on homebrew being installed already
- name: prepare Brewfile
  template: dest="~/Library/Preferences/Brewfile" mode=0644 src=Brewfile

- name: bundle
  command: brew bundle chdir="~/Library/Preferences"
  register: bundle_out

- debug: var=bundle_out.stdout_lines

- name: clean up old versions
  command: brew cleanup
  register: cleanup_out

- debug: var=cleanup_out.stdout_lines
