# Docs: https://dependabot.com/docs/config-file/
version: 1

update_configs:
  - package_manager: 'javascript'
    directory: 'files/.config/coc/extensions'
    update_schedule: 'live'
    allowed_updates:
      - match:
          update_type: 'security'
    automerged_updates:
      - match:
          dependency_type: 'production'
          update_type: 'security:patch'
      - match:
          dependency_type: 'development'
          update_type: 'security:patch'
